name: Auto Deployment

on:
  push:
    branches: [ master, woog2roid-ghactions_autodeploy ]

env:
  REACT_APP_KAKAO_API_KEY: ${{secrets.REACT_APP_KAKAO_API_KEY}}
  REACT_APP_SEOUL_API_KEY: ${{secrets.REACT_APP_SEOUL_API_KEY}}
  REACT_APP_DEV_API_DOMAIN: ${{secrets.REACT_APP_DEV_API_DOMAIN}}
  REACT_APP_API_DOMAIN: ${{secrets.REACT_APP_API_DOMAIN}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - run : npm i
      shell: bash
    - run : npm ci
      shell: bash
    - run : git config user.name github-actions
      shell: bash
    - run : git config user.email github-actions@github.com
      shell: bash
    - run :  CI=false npm run deploy
      shell: bash
